[package]
name = "backend"
version = "1.0.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
araucaria = { git = "https://github.com/joao-arthur/araucaria", rev = "9cd2626e5847b53d0facc1eb22e24a317a41fbf4" }
araucaria_plugins = { git = "https://github.com/joao-arthur/araucaria_plugins", rev = "9eb11410f2a7fde56d0c95f7d389af29156e46f5" }
domain = { path = "../domain" }
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0"
uuid = { version = "1.11.0", features = [ "v4"] }
chrono = "0.4.39"
jsonwebtoken = "9.3.0"
email_address = "0.2.9"
regex = "1.11.1"
accept-language = "3.1.0"
rust-i18n = "3.1.2"
 