[package]
name = "backend"
version = "1.0.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
araucaria = { git = "https://github.com/joao-arthur/araucaria", rev = "300b4eeed0af3362882ab7ce8559cfc342dfffe6" }
araucaria_plugins = { git = "https://github.com/joao-arthur/araucaria_plugins", rev = "c7bb425212f8e120a1202f50eac222003f89e49b" }
domain = { path = "../domain" }
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0.140"
uuid = { version = "1.11.0", features = [ "v4"] }
chrono = "0.4.40"
jsonwebtoken = "9.3.0"
email_address = "0.2.9"
regex = "1.11.1"
accept-language = "3.1.0"
rust-i18n = "3.1.2"
 