[package]
name = "domain"
version = "1.0.0"
edition = "2021"
license = "AGPL-3.0"

[lib]
crate-type = ["rlib"]
bench = false

[dependencies]
araucaria = { git = "https://github.com/joao-arthur/araucaria", rev = "9cd2626e5847b53d0facc1eb22e24a317a41fbf4" }
